# Generated by Django 5.1.4 on 2024-12-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_title', models.CharField(error_messages={'required': 'Please provide an entry title'}, max_length=255)),
                ('entry_location', models.CharField(error_messages={'required': 'Please provide an entry location'}, max_length=255)),
                ('entry_body', models.TextField(error_messages={'required': 'Please provide the entry body'})),
                ('entry_index', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
