# Generated by Django 5.1.4 on 2024-12-20 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_remove_entry_created_by'),
        ('user', '0002_remove_user_confirm_password_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='user.user'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
