# Generated by Django 5.1.4 on 2024-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(error_messages={'required': 'Please provide your full name'}, max_length=255)),
                ('email', models.EmailField(error_messages={'invalid': 'Enter a valid email address', 'required': 'Please provide your email address'}, max_length=254, unique=True)),
                ('password', models.CharField(error_messages={'required': 'Please provide your password'}, max_length=128)),
                ('confirm_password', models.CharField(error_messages={'required': 'Please confirm your password'}, max_length=128)),
                ('profile_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
